version: '3.8'

services:
  nginx:
    container_name: multer-nginx
    restart: always
    build:
      context: ./nginx
    ports:
      - '80:80'

  api:
    container_name: multer-nestapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000' # host : docker